import pickle
import pandas as pd
import numpy as np

with open (r"Olx_WagonR_Scraping/database/tab_dict.pkl","rb") as file:
    f = pickle.load(file=file)

df = pd.DataFrame(f )

# for i in df:
#     print(i , df[i].nunique())

rep_location = {
    'Mumbai': 'Mumbai',
    'Kolhapur': 'Kolhapur',
    'Navi Mumbai': 'Thane',
    'Pune': 'Pune',
    'Nashik': 'Nashik',
    'Ahmadnagar': 'Ahmednagar',
    'Thane': 'Thane',
    'Nagpur': 'Nagpur',
    'Sangli (-Miraj)': 'Sangli',
    'Aurangabad': 'Aurangabad',
    'Sangli Miraj Kupwad': 'Sangli',
    'Amravati': 'Amravati',
    'Lakhamapur MIDC': 'Nashik',
    'Wardha': 'Wardha',
    'Palghar': 'Palghar',
    'Satara': 'Satara',
    'Kurkumbh MIDC': 'Pune',
    'Khopoli': 'Raigad',
    'Bhiwandi': 'Thane',
    'Jalgaon': 'Jalgaon',
    'Badlapur': 'Thane',
    'Yavatmal': 'Yavatmal',
    'Neral': 'Raigad',
    'Chandrapur': 'Chandrapur',
    'Ichalkaranji': 'Kolhapur',
    'Umarga': 'Osmanabad',
    'Ratnagiri': 'Ratnagiri',
    'Chakan': 'Pune',
    'Dapoli': 'Ratnagiri',
    'Mahad': 'Raigad',
    'Latur': 'Latur',
    'Miraj': 'Sangli',
    'Chalisgaon': 'Jalgaon',
    'Navghar-Manikpur': 'Thane',
    'Sawantwadi': 'Sindhudurg',
    'Ajanta': 'Aurangabad',
    'Kudal MIDC': 'Sindhudurg',
    'Uran Islampur': 'Sangli',
    'Baramati': 'Pune',
    'Bhusawal': 'Jalgaon',
    'Gadhinglaj': 'Kolhapur',
    'Dehu Cantt': 'Pune',
    'Ganpatipule': 'Ratnagiri',
    'Phaltan': 'Satara',
    'Kopargaon': 'Ahmednagar',
    'Junnar': 'Pune',
    'Ashta': 'Sangli',
    'Mahad MIDC': 'Raigad',
    'Karad': 'Satara',
    'Ganeshpur': 'Kolhapur',
    'Mahapoli': 'Thane',
    'Parbhani': 'Parbhani',
    'Lonand': 'Satara',
    'Malegaon Jahangir': 'Washim',
    'Raigad District': 'Raigad',
    'Jalna': 'Jalna',
    'Faizpur': 'Jalgaon',
    'Nanded Waghala': 'Nanded',
    'Niphad': 'Nashik',
    'Kagal': 'Kolhapur',
    'Kudus': 'Palghar',
    'Chiplun': 'Ratnagiri',
    'Chikhli': 'Buldhana',
    'Ausa': 'Latur',
    'Ulhasnagar': 'Thane',
    'Akola': 'Akola',
    'Nandgaon': 'Nashik',
    'Pen': 'Raigad',
    'Ambajogai': 'Beed',
    'Shirpur': 'Dhule',
    'Loni': 'Ahmednagar',
    'Walwa': 'Sangli',
    'Chitegaon': 'Aurangabad',
    'Tumsar': 'Bhandara',
    'Manmad': 'Nashik',
    'Waluj MIDC': 'Aurangabad',
    'Madangad': 'Ratnagiri',
    'Malwan': 'Sindhudurg',
    'Raver': 'Jalgaon',
    'Shrirampur': 'Ahmednagar',
    'Jaysingpur': 'Kolhapur',
    'Dhule': 'Dhule',
    'Rahuri': 'Ahmednagar',
    'Hupari': 'Kolhapur',
    'Vaibhawadi': 'Sindhudurg',
    'Shirur': 'Pune',
    'Gondiya': 'Gondia',
    'Daund': 'Pune',
    'Shirala': 'Sangli',
    'Ahmadpur': 'Latur',
    'Sindhudurg': 'Sindhudurg',
    'Georai': 'Beed',
    'Atgaon Industrial Complex': 'Thane',
    'Shirur Kasar': 'Beed',
    'Murbad': 'Thane',
    'Latur Industrial Area Additional': 'Latur',
    'Shirol': 'Kolhapur',
    'Boisar': 'Palghar',
    'Vaduj': 'Satara',
    'Alibag': 'Raigad',
    'Kavathe Mahankal': 'Sangli',
    'Vijay Durg': 'Sindhudurg',
    'Kudal': 'Sindhudurg',
    'Pulgaon': 'Wardha',
    'Chinchwad': 'Pune',
    'Kankavli': 'Sindhudurg',
    'Erandol': 'Jalgaon',
    'Barsi': 'Solapur',
    'Solapur': 'Solapur',
    'Anjangaon': 'Amravati',
    'Warora': 'Chandrapur',
    'Yeola': 'Nashik',
    'Bhum': 'Osmanabad',
    'Ozar': 'Nashik',
    'Kavalapur': 'Sangli',
    'Gangakhed': 'Parbhani',
    'Shrigonda': 'Ahmednagar',
    'Hatkanangle': 'Kolhapur',
    'Mandur': 'Aurangabad',
    'Shahada': 'Nandurbar',
    'Hinganghat': 'Wardha',
    'Ranjangaon MIDC': 'Pune',
    'Khandala Satara': 'Satara',
    'Udgir': 'Latur',
    'Babhaleshwar': 'Ahmednagar',
    'Malkapur Kolhapur District': 'Kolhapur',
    'Kurundvad': 'Kolhapur',
    'Devgad': 'Sindhudurg',
    'Nandurbar': 'Nandurbar',
    'Ambad': 'Jalna',
    'Wai': 'Satara',
    'Chandurbazar': 'Amravati',
    'Malegaon': 'Nashik',
    'Amboli': 'Sindhudurg',
    'Gargoti': 'Kolhapur',
    'Pirangut': 'Pune',
    'Ashti MIDC': 'Beed',
    'Mahoor': 'Nanded',
    'Washi': 'Osmanabad',
    'Ballarpur': 'Chandrapur',
    'Dapoli Camp': 'Ratnagiri',
    'Bhandara': 'Bhandara',
    'Osmanabad': 'Osmanabad',
    'Karalewadi': 'Pune',
    'Lanja': 'Ratnagiri',
    'Pandharpur': 'Solapur',
    'Tasgaon': 'Sangli',
    'Nanded': 'Nanded'
}

df['Location'] = df['Location'].replace(rep_location)

rep_variant = {
    'wagon-r-cng-lxi': 'lxi',
    'wagon-r-lxi': 'lxi',
    'maruti-suzuki-wagon-r-vxi-1.0-cng': 'vxi',
    'wagon-r-lxi-cng-optional': 'lxi',
    'wagon-r-cng-lxi-opt': 'lxi',
    'wagon-r-vxi': 'vxi',
    'nan': np.nan,
    'wagon-r-lxi-cng': 'lxi',
    'wagon-r-amt-vxi': 'vxi',
    'maruti-suzuki-wagon-r-vxi-ags-1.0l': 'vxi',
    'maruti-suzuki-wagon-r-lxi-1.0': 'lxi',
    'version-VXI Automatic': 'vxi',
    'maruti-suzuki-wagon-r-vxi-ags-1.2l': 'vxi',
    'wagon-r-lxi-opt': 'lxi',
    'maruti-suzuki-wagon-r-zxi': 'zxi',
    'wagon-r-vxi-amt-opt-1.2': 'vxi',
    'version-Wagonr R VXI + AMT-3671': 'vxi',
    'maruti-suzuki-wagon-r-1.2-zxi': 'zxi',
    'maruti-suzuki-wagon-r-vxi-1.0': 'vxi',
    'maruti-suzuki-wagon-r-vxi-mt-1.2l': 'vxi',
    'wagon-r-vxi-1.2': 'vxi',
    'wagon-r-2010-2012-lxi-cng': 'lxi',
    'version-Wagon R VXi with ABS Minor-1626': 'vxi',
    'maruti-suzuki-wagon-r-lxi-minor': 'lxi',
    'wagon-r-lxi-bs-iv': 'lxi',
    'wagon-r-2010-2012-lxi-bs-iv': 'lxi',
    'wagon-r-vxi-bs-iv': 'vxi',
    'maruti-suzuki-wagon-r-vxi-abs-airbag': 'vxi',
    'maruti-suzuki-wagon-r-zxi-ags-1.2l': 'zxi',
    'wagon-r-vxi-amt-opt': 'vxi',
    'wagon-r-pro': 'wagon-r-pro',
    'wagon-r-zxi-1.2': 'zxi',
    'wagon-r-vxi-amt': 'vxi',
    'wagon-r-2010-2012-lxi-bsiii': 'lxi',
    'wagon-r-vxi-plus-optional': 'vxi',
    'maruti-suzuki-wagon-r-vxi-minor': 'vxi',
    'version-Wagon R LXi Minor-1624': 'lxi',
    'maruti-suzuki-wagon-r-ax-minor': 'maruti-suzuki-wagon-r-ax-minor',
    'maruti-suzuki-wagon-r-vxi-mt-1.0l': 'vxi',
    'wagon-r-lxi-optional': 'lxi',
    'wagon-r-amt-vxi-plus-option': 'vxi',
    'wagon-r-vxi-optional': 'vxi',
    'maruti-suzuki-wagon-r-1.2-zxi-plus': 'zxi',
    'maruti-suzuki-wagon-r-lxi-mt-1.0l': 'lxi',
    'maruti-suzuki-wagon-r-zxi-mt-1.2l': 'zxi',
    'wagon-r-amt-vxi-option': 'vxi',
    'wagon-r-lx-bs-iv': 'wagon-r-lx-bs-iv',
    'maruti-suzuki-wagon-r-lx-minor': 'maruti-suzuki-wagon-r-lx-minor',
    'wagon-r-lxi-cng-avance-edition': 'lxi',
    'wagon-r-2010-2012-ax': 'wagon-r-2010-2012-ax',
    'version-Wagon R VXi Minor-1625': 'vxi',
    'wagon-r-2010-2012-ax-bsii': 'wagon-r-2010-2012-ax-bsii',
    'version-Wagon R LX Minor-1623': 'version-Wagon R LX Minor-1623',
    'wagon-r-diesel': 'wagon-r-diesel',
    'maruti-suzuki-wagon-r-vxi-plus-mt': 'vxi',
    'maruti-suzuki-wagon-r-lxi-signature-edition': 'lxi',
    'wagon-r-2010-2012-ax-bsiv': 'wagon-r-2010-2012-ax-bsiv',
    'maruti-suzuki-wagon-r-vxi-plus(o)': 'vxi',
    'version-Wagon R AX Minor-1620': 'version-Wagon R AX Minor-1620',
    'wagon-r-2010-2012-lx-bs-iv': 'wagon-r-2010-2012-lx-bs-iv',
    'maruti-suzuki-wagon-r-1.2-zxi-plus-dual-tone': 'zxi',
    'maruti-suzuki-wagon-r-vxi-felicity-edition': 'vxi',
    'maruti-suzuki-wagon-r-zxi-automatic': 'zxi',
    'wagon-r-vxi-plus': 'vxi',
    'wagon-r-vxi-opt-1.2': 'vxi',
    'wagon-r-zxi-amt-1.2': 'zxi',
    'wagon-r-2010-2012-ax-minor': 'wagon-r-2010-2012-ax-minor',
    'wagon-r-2010-2012-lxi-bsii': 'lxi',
    'maruti-suzuki-wagon-r-flex-fuel': 'maruti-suzuki-wagon-r-flex-fuel',
    'wagon-r-vxi-opt': 'vxi',
    'wagon-r-lxi-avnace-edition': 'lxi',
    'maruti-suzuki-wagon-r-zxi-ags-1.2': 'zxi',
    
}


df['Variant'] = df['Variant'].replace(rep_variant)

variant_rep2 = {'wagon-r-pro': 'pro', 
                'maruti-suzuki-wagon-r-ax-minor' : 'ax minor',
                'wagon-r-lx-bs-iv' : 'lxi', 
                'maruti-suzuki-wagon-r-lx-minor' : 'lx minor',
                'wagon-r-2010-2012-ax' : 'ax minor', 
                'wagon-r-2010-2012-ax-bsii' : 'ax minor',
                'version-Wagon R LX Minor-1623' : 'lx minor', 
                'wagon-r-diesel' : 'lxi',
                'wagon-r-2010-2012-ax-bsiv' : 'ax minor', 
                'version-Wagon R AX Minor-1620' : 'ax minor',
                'wagon-r-2010-2012-lx-bs-iv' : 'lxi', 
                'wagon-r-2010-2012-ax-minor' : 'ax minor',
                'maruti-suzuki-wagon-r-flex-fuel' : 'flex'}

df['Variant'] = df['Variant'].replace(variant_rep2)

df = df.drop(['Posted on','Brand','Model','Transmission'],axis=1)

df = df.dropna(axis=0)

df['KM driven'] = df['KM driven'].astype(int)
df['Price'] = df['Price'].astype(int)

df['KM driven'] = df['KM driven'].apply(lambda i : int(np.floor(i/1000)*1000) if i>1000 else 1000)

df = df.groupby(['Year','Location','Variant','Fuel','KM driven'])['Price'].agg(['count','mean'])

df.to_csv('Olx_WagonR_Scraping/database/WagonR_DB_Cleaned.csv')
  

    